<?php  if ( ! defined("BASEPATH")) exit("No direct script access allowed");
$config["protocol"]="smtp";
$config["smtp_host"]="https://first-class-hydraul.000webhostapp.com/";
$config["smtp_port"]="465";
$config["smtp_timeout"]="30";
$config["smtp_user"]="patelaruvishal@gmail.com";
$config["smtp_pass"]="Lion@7275";
$config["charset"]="utf-8";
$config["newline"]="\r\n";
$config["mailtype"]="textdomain";
